# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    "@openzeppelin/contracts=lib/openzeppelin-contracts/contracts",
    "@chainlink/contracts/=lib/chainlink-brownie-contracts/contracts/",
]

[fmt]
# [fmt]: code formatter options for `forge fmt`.
# These control formatting behavior such as bracket spacing, preferred quote style,
# line length, and other stylistic preferences applied during formatting.
bracket_spacing = true
int_types = "long"
line_length = 120
multiline_func_header = "all"
number_underscore = "thousands"
quote_style = "double"
tab_width = 4
wrap_comments = true

# 
[invariant]
# [invariant]: configuration for the invariant checker.
# - runs: number of fuzzing runs to attempt when checking invariants.
# - depth: call depth limit during invariant checks.
# These values balance thoroughness and runtime; adjust as needed for CI or local runs.
runs = 100
depth = 128
fail_on_revert = true
